version: 2

updates:
  - package-ecosystem: "github-actions" 
    directory: "/" 
    target-branch: "main"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm" 
    directory: "/" 
    target-branch: "main"
    schedule:
      interval: "monthly"