name: Publish Package

on:
    push:
        branches: [main]

env:
    NODE_VERSION: 18.x
    GITHUB_PACKAGE_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN}}
    NPM_ACCESS_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN }}

jobs:
    publish-pkg:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{env.NODE_VERSION}}

            - name: Copying config files
              run: cp ./.npmrc ~/.npmrc
              shell: bash

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            # - name: Linting
            #   run: yarn lint --format junit -o reports/junit/js-lint-results.xml
        
            - name: Typechecking
              run: yarn typecheck

            - name: Publish npm pkg
              run: npm publish --access restricted